name = "delete"
version = "0.1.0"
language = "rust"
type = "component"

[component]
wit_world = "main"
wasm_target = "wasm32-wasip2"

[[registry.pull.sources]]
target = "betty-blocks:crud/crud"
source = "file://./external/crud.wit"

[[registry.pull.sources]]
target = "betty-blocks:data-api/data-api"
source = "file://./external/data-api.wit"
