name: Build and Release WASM Component

on:
  push:
    # This workflow runs only when you push a tag that starts with 'v'
    tags:
      - "v*"

jobs:
  create-release:
    runs-on: ubuntu-latest
    permissions:
      # This permission is required to create a release and upload assets
      contents: write
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install stable Rust toolchain
        uses: dtolnay/rust-toolchain@1.88.0
        with:
          targets: wasm32-wasip2

      - uses: taiki-e/install-action@v2
        with:
          tool: just,wkg,wash

      - run: for d in components/*/; do just -f "$d/Justfile" build; done
      - run: wash build -p ./helper/http-wrapper
      - run: wash build -p ./helper/data-api/component

      - name: Create GitHub Release and Upload WASM Asset
        uses: softprops/action-gh-release@v2
        with:
          # This command will automatically create a release using the tag name
          # that triggered the workflow. It will then upload the files listed below.
          files: |
            target/wasm32-wasip2/release/*.wasm
            helper/http-wrapper/build/http_wrapper_s.wasm
            helper/data-api/component/build/crud_component_s.wasm
        env:
          # The GITHUB_TOKEN is a secret automatically provided by GitHub Actions
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Publish to GitHub Packages
        run: |
          VERSION=$(wash inspect ./helper/http-wrapper/build/http_wrapper_s.wasm -o json | jq -r '.version')
          wash push --user ${{github.actor}} --password ${{ secrets.GITHUB_TOKEN }} ghcr.io/${{ github.repository_owner }}/http-wrapper:$VERSION helper/http-wrapper/build/http_wrapper_s.wasm
      - name: Publish to GitHub Packages
        run: |
          VERSION=$(wash inspect ./helper/data-api/component/build/crud_component_s.wasm -o json | jq -r '.version')
          wash push --user ${{github.actor}} --password ${{ secrets.GITHUB_TOKEN }} ghcr.io/${{ github.repository_owner }}/crud-component:$VERSION helper/data-api/component/build/crud_component_s.wasm
