name: Release WASM Components to Betty Blocks

on:
  push:
    branches: ["main", "acceptance", "edge"]

jobs:
  publish:
    runs-on: ubuntu-latest
    environment: ${{ github.ref_name }}
    steps:
      - uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest
      - run: npm config set '//registry.npmjs.org/:_authToken' '${{ secrets.NPM_TOKEN }}'

      - name: Install dependencies
        run: bun install --frozen-lockfile

      - name: Publish to Betty Blocks
        run: bun run publish.ts ${{ secrets.BLOCKSTORE_CLI_SECRET }} ${{ github.ref_name }}
